name: NodeJS Package

on:
  push:
    paths:
      - 'src/*'
      - '*.js'
      - '*.json'
  pull_request:
    paths:
      - 'src/*'
      - '*.js'
      - '*.json'

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8, 10]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      